title: "Data Mining in R"
description: "By Xiaorui Zhu & Yan Yu <br /> The greatest truths are the simplest. -- Tao Te Ching <br /> Thinking details thoughtfully, solving in whole elegantly. -- Xiaorui Zhu"
show_downloads: FALSE
google_analytics:
theme: jekyll-theme-cayman
google_analytics: [UA-54280540-4]
