title: Data Mining in R
description: This set of notes for undergraduate and graduate data mining class is currently maintained by Xiaorui Zhu(zhuxiaorui1989@gmail.com). Many materials are from Dr. Yan Yu's previous class notes. And lab notes are from three previous PhD students in Lindner College of Business.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
markdown: redcarpet
