title: "Data Mining in R"
description: "The greatest truths are the simplest -- Tao Te Ching. Thinking details thoughtfully, solving in whole elegantly. "
show_downloads: FALSE
google_analytics:
theme: jekyll-theme-cayman
